INPUT "ALAS SEGITIGA"; X
INPUT "TINGGI SEGITIGA"; Y
G = 1 / 2 * X * Y
PRINT "HASIL SEGITIGA"; G
IF G > 100 THEN
    KET$ = "tidak memungkinkan"
ELSEIF G < 100 THEN
    KET$ = " MEMUNGKINKAN"
ELSE
    KET$ = " COCOK "
END IF
PRINT KET$

